spring:
  ## redis链接
  redis:
    database: 0
    ## 如果是单点的redis，打开以下配置 start
    host: xxx.xx.xx.xxx
    port: 6379
    ## 单点redis配置结束 end
    password: 123456
    redisson:
      file: classpath:redisson.yml
    ## 如果是sentinel，打开以下配置 start
#    sentinel:
#      master: mymaster
#      nodes: [xxx.xx.x.xx:26379,xxx.xx.x.xx:26379,xxx.xx.x.xx:26379]
    ## sentinel配置结束
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
